---
title: "Clustering"
author: "Seema Plaisier"
date: "`r format(Sys.time(), '%m/%d/%y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)

```

### Libraries
```{r}
library(pheatmap)
library(readxl)

```


### session Info
```{r, eval=TRUE}

sessionInfo()

```


### Load data
```{r}
genesTXT = "C:/Users/splaisie/Documents/PlacentaScratch/methylation/other_files/XCI_data_all_XX_placenta.txt"

data = read.delim(genesTXT, sep = "\t", header = TRUE, row.names = 1, check.names = FALSE)
df = as.data.frame(data)
df = na.exclude(df)

df_escape = df[df$XCI_status == "escape",]
df_inactivated = df[df$XCI_status == "inactivated",]
df_variable = df[df$XCI_status == "variable",]

genesTXT2 = "C:/Users/splaisie/Documents/PlacentaScratch/methylation/other_files/XCI_data_all_XX_placenta_filterfigure.txt"

data2 = read.delim(genesTXT2, sep = "\t", header = TRUE, row.names = 1, check.names = FALSE)
df2 = as.data.frame(data2)
df2 = na.exclude(df2)

df_escape2 = df2[df2$XCI_status == "escape",]
df_inactivated2 = df2[df2$XCI_status == "inactivated",]
df_variable2 = df2[df2$XCI_status == "variable",]

```

### Clustering
```{r}

outfile = gsub(".txt","_escape_heatmap.pdf", genesTXT)
clustertree = pheatmap(mat = as.matrix(df_escape[,2:9]), color = colorRampPalette(c("blue","white","red"))(100), border_color = NA, cluster_cols = FALSE, cluster_rows = FALSE, fontsize = 10, show_rownames = TRUE, main = "", filename = outfile)

outfile = gsub(".txt","_inactivated_heatmap.pdf", genesTXT)
clustertree = pheatmap(mat = as.matrix(df_inactivated[,2:9]), color = colorRampPalette(c("blue","white","red"))(100), border_color = NA, cluster_cols = FALSE, cluster_rows = FALSE, fontsize = 4, show_rownames = TRUE, main = "", filename = outfile)

outfile = gsub(".txt","_inactivated_heatmap.pdf", genesTXT2)
clustertree = pheatmap(mat = as.matrix(df_inactivated2[,2:9]), color = colorRampPalette(c("blue","white","red"))(100), border_color = NA, cluster_cols = FALSE, cluster_rows = FALSE, fontsize = 7, show_rownames = TRUE, main = "", filename = outfile)

outfile = gsub(".txt","_variable_heatmap.pdf", genesTXT)
clustertree = pheatmap(mat = as.matrix(df_variable[,2:9]), color = colorRampPalette(c("blue","white","red"))(100), border_color = NA, cluster_cols = FALSE, cluster_rows = FALSE, fontsize = 10, show_rownames = TRUE, main = "", filename = outfile)

```

